CREATE DATABASE [TestDB1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDB1', FILENAME = N'C:\1\TestDB1.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestDB1_log', FILENAME = N'C:\1\TestDB1_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE Latin1_General_CI_AI 

GO

 CREATE DATABASE [TestDB2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDB2', FILENAME = N'C:\1\TestDB2.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestDB2_log', FILENAME = N'C:\1\TestDB2_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE Latin1_General_CS_AS 